/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class baiduaudio_tangdi_com_jnitest_JNiClassUntils */

#ifndef _Included_baiduaudio_tangdi_com_jnitest_JNiClassUntils
#define _Included_baiduaudio_tangdi_com_jnitest_JNiClassUntils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     baiduaudio_tangdi_com_jnitest_JNiClassUntils
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_baiduaudio_tangdi_com_jnitest_JNiClassUntils_helloJni
  (JNIEnv *, jobject);
        /* JNIEnv是一个指向JNIEnv的指针类型*/

/*
 * Class:     baiduaudio_tangdi_com_jnitest_JNiClassUntils
 * Method:    getKeys
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_baiduaudio_tangdi_com_jnitest_JNiClassUntils_getKeys
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
